name: ResNet
is_DL: True

contrastive: True

in_channels: 64
kernel_size_1: 7
stride_1: 2
padding_1: 3
kernel_size_2: 3
stride_2: 2
padding_2: 1

num_classes: 2
num_layers: 18
layers: [2,2,2,2]
projection_dim: 128

# Loss
temperature: 0.5

# LR
optimiser: Adam
lr: 0.0001